# Generated by Django 2.2.4 on 2020-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0005_auto_20201021_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
            preserve_default=False,
        ),
    ]
