# Generated by Django 2.2.4 on 2020-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0006_auto_20201021_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='message',
            field=models.ManyToManyField(related_name='car_messages', to='cars_app.User'),
        ),
    ]
